name: Matrix Output

on:
  workflow_dispatch:

jobs:
  run-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    outputs:
      out: ${{ toJSON(steps) }}
    steps:
      - name: Set Output
        id: matrix-step
        run: |
          echo "::set-output name=${{ matrix.version }}::x${{ matrix.version }}"
  output:
    needs: run-matrix
    runs-on: ubuntu-latest
    steps:
      - env:
          NEEDS: ${{ toJSON(needs) }}
        run: echo "$NEEDS"
