name: Matrix Output

on:
  workflow_dispatch:

jobs:
  run-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ["AA", "BB", "CC"]
    outputs:
      out: ${{steps.sout.outputs.${{ matrix.value }}}}
    steps:
      - name: Set Output
        id: sout
        run: |
          echo "::set-output name=${{ matrix.value }}::x${{ matrix.value }}"
  output:
    needs: run-matrix
    runs-on: ubuntu-latest
    steps:
      - env:
          NEEDS: ${{ toJSON(needs) }}
        run: |
          jq -r '."run-matrix".outputs.out' <<< "$NEEDS" | jq .
