name: Matrix Output

on:
  workflow_dispatch:

jobs:
  run-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ["AA", "BB", "CC", "_END_"]
#    outputs:
#      out: ${{steps}}
    steps:
      - name: Set Output
        id: sout
        run: |
          echo "::set-output name=${{ matrix.value }}::x${{ matrix.value }}"
      - if: ${{ matrix.value == '_END_' }}
        env:
          STEPS: ${{ toJSON(steps) }}
        run: |
          jq . <<< "$STEPS"
  output:
    needs: run-matrix
    runs-on: ubuntu-latest
    steps:
      - env:
          NEEDS: ${{ toJSON(needs) }}
        run: |
          jq -r '."run-matrix"' <<< "$NEEDS" | jq .
