name: Matrix Output

on:
  workflow_dispatch:

jobs:
  run-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    outputs:
      out: ${{ toJSON(steps) }}
    steps:
      - name: Set Output
        id: format('{{step-{0}}}', ${{ matrix.version }})
        run: |
          echo "::set-output name=value::x${{ matrix.version }}"
  output:
    needs: run-matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{toJSON(needs.matrix.outputs)}}
