name: Matrix Output

on:
  workflow_dispatch:

jobs:
  run-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ["AA", "BB"]
    steps:
      - name: Set Output
        id: sout
        run: |
          echo "::set-output name=${{ matrix.value }}::x${{ matrix.value }}"
  output:
    needs: run-matrix
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          jq -r '."run-matrix".outputs.job' <<< "$NEEDS" | jq .
          gh api '/repos/efernandesng/github-workflows-PoCs/actions/runs' -F runId=${{github.run_id}}
