name: Matrix Output

on:
  workflow_dispatch:

jobs:
  run-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ["AA", "BB"]
    steps:
      - name: Set Output
        id: sout
        run: |
          echo "::notice file=app.js::${{ matrix.value }}"
          #echo "::set-output name=${{ matrix.value }}::x${{ matrix.value }}"

  output:
    needs: run-matrix
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}  
        run: |
          check_run_url=$(gh api '/repos/efernandesng/github-workflows-PoCs/actions/runs/${{github.run_id}}/jobs' | jq -r '.jobs[].check_run_url')
          # gh api "$check_run_url/annotations"
          while IFS= read -r url; do
            gh api "$url/annotations" | jq '.[0].message'
          done <<< "$check_run_url"
