name: Matrix Output

on:
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          values: [1,2,3]
    outputs:
      out: ${{ steps }}
    steps:
      - name: Set Output
        run: |
          echo "::set-output name=value::x${{ matrix.values }}"
  output:
    needs: matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{toJSON(needs.matrix.outputs)}}
