name: Matrix Output

on:
  workflow_dispatch:

jobs:
  run-matrix:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          value: [1,2,3]
    outputs:
      out: ${{ toJSON(steps) }}
    steps:
      - name: Set Output
        id: format('{{step-{0}}}', ${{ matrix.value }})
        run: |
          echo "::set-output name=value::x${{ matrix.value }}"
  output:
    needs: run-matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{toJSON(needs.matrix.outputs)}}
